config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'
  resources :questions, only: [:index, :show, :new, :create] do
    resources :answers, except: [:index, :show, :new]
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  validates :body, length: {minimum: 10}
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
  validates :body, length: {minimum: 10}
  validates :details, length: {minimum: 10}
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    question = Question.find(params[:question_id])
    redirect_to question_path(question)
  end

  def create
    @answer = Answer.new(answer_params)
    @question = Question.find(params[:question_id])
    @answer.question = @question
    if @answer.save
      flash[:notice] = 'Answer was successfully created.'
      redirect_to question_path(@question)
    else
      flash[:notice] = @answer.errors.full_messages.join(" & ")
      render :new
    end
  end

  def edit
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
  end

  def update
    @answer = Answer.find(params[:id])
    @question = Question.find(params[:question_id])
    @answer.question = @question
    if @answer.update_attributes(answer_params)
      flash[:notice] = 'Answer was successfully updated.'
      redirect_to question_path(@question)
    else
      flash[:notice] = @answer.errors.full_messages.join(" & ")
      render :edit
    end
  end

  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy
    flash[:notice] = 'Answer Absolutely Destroyed'
    redirect_to '/questions/'+params[:question_id]
  end

  private
  def answer_params
    params.require(:answer).permit(:body, :question_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.order(created_at: :desc)
  end

  def show
    @question = Question.find(params['id'])
    @answers = @question.answers
    @answer = Answer.new
  end

  def new
    @question = Question.new
  end

  def create
    # binding.pry
    @question = Question.new(question_params)

    if @question.save
      flash[:notice] = 'Article was successfully created.'
      redirect_to @question
    else
      flash[:notice] = @question.errors.full_messages.join(" & ")
      render 'new'
    end
  end

  private

  def question_params
    params.require(:question).permit(:body, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/edit.html.erb
<%= form_for [@question, @answer] do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit "Add Answer" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%- flash.each do |key, value| -%>
      <div class="flash flash-<%= key %>">
        <%= value %>
      </div>
    <%- end -%>

    <%= yield %>

  </body>
</html>

app/views/questions/index.html.erb
<h1>Questions</h1>

<ul>
  <% @questions.each do |question| %>
    <li><%= link_to question.body, "/questions/" + question.to_param %></li>
  <% end %>
</ul>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= form_for(@question) do |f| %>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>

  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_field :details %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<h1><%= @question.body %></h1>

<div class="question_details"><%= @question.details %></div>

<ul>
  <% @answers.each do |answer| %>
    <li><%= answer.body %> (<%= link_to "edit", edit_question_answer_path(@question, answer) %>, <%= link_to "delete", question_answer_path(@question, answer), method: :delete %>) </li>
  <% end %>
</ul>

<%= form_for [@question, @answer] do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit "Add Answer" %>
<% end %>


<div class="back">
  <%= link_to "back", "/questions/" %>
</div>